### ISSUE TITLE
Event Mapping Error

### ISSUE THREAD

**Issue by mokko** [mokko/zml2lido#38]
Writing back to C:\m3\zml2lido\sdata\DDB\20220104\group29875-chunk1-links.onlyPub.lido.xml
VALIDATING LIDO
 loading schema C:\m3\zml2lido\zml2lido\data\xsd\lido-v1.0.xsd
 validating...
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Python\Scripts\lido.exe\__main__.py", line 7, in <module>
  File "C:\m3\zml2lido\zml2lido\__init__.py", line 30, in lido
    getattr(m, args.job)()
  File "C:\m3\zml2lido\zml2lido\lidoTool.py", line 148, in smb
    self.validate(input=linklido_fn)
  File "C:\m3\zml2lido\zml2lido\lidoTool.py", line 274, in validate
    print(" validating...")
  File "src\lxml\etree.pyx", line 3648, in lxml.etree._Validator.assert_
AssertionError: Element '{http://www.lido-schema.org}event': Character content other than whitespace is not allowed because the content type is 'element-only'., line 96

**Comment by mokko** [comment]
Fixed
