### ISSUE TITLE
KK-vanGogh-join-group154397.xml keine Umformung zml2lido

### ISSUE THREAD

**Issue by FrankvonHagel** [mokko/zml2lido#86]
Bei dieser Datei hakt es wieder, erkenne aber den Fehler nicht
[KK-vanGogh-join-group154397.xml.zip](https://github.com/mokko/zml2lido/files/10094783/KK-vanGogh-join-group154397.xml.zip)

H:\Documents\py\zml2lido>lido -j smb -i H:\Documents\py\MpApi\sdata\KK-vanGogh\KK-vanGogh\20221125\KK-vanGogh-join-group154397.xml
JOB: smb
SCRIPT_DIR: \\FS0002\Home\MDFRAHAG\Documents\py\zml2lido
Making new dir \\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\sdata\KK-vanGogh\20221125
 outdir \\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\sdata\KK-vanGogh\20221125
ZML2LIDO
        new
java -Xmx1450m -jar H:\Documents\py\SaxonHE10-5J\saxon-he-10.5.jar -s:H:\Documents\py\MpApi\sdata\KK-vanGogh\KK-vanGogh\20221125\KK-vanGogh-join-group154397.xml -xsl:\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\zml2lido\data\xsl\zml2lido.xsl -o:\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\sdata\KK-vanGogh\20221125\KK-vanGogh-join-group154397.lido.xml
Error occurred during initialization of VM
Could not reserve enough space for 1484800KB object heap
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mdfrahag\AppData\Roaming\Python\Python310\Scripts\lido.exe\__main__.py", line 7, in <module>
  File "\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\zml2lido\__init__.py", line 79, in lido
    getattr(m, args.job)()
  File "\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\zml2lido\jobs.py", line 93, in smb
    lido_fn = self.zml2lido(Input=self.Input)
  File "\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\zml2lido\lidoTool.py", line 312, in zml2lido
    return self.zml2lidoSingle(Input=Input)
  File "\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\zml2lido\lidoTool.py", line 321, in zml2lidoSingle
    self.saxon(Input=inputP, xsl=xsl["zml2lido"], output=lidoFn)
  File "\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\zml2lido\lidoTool.py", line 368, in saxon
    subprocess.run(
  File "C:\Program Files\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'java -Xmx1450m -jar H:\Documents\py\SaxonHE10-5J\saxon-he-10.5.jar -s:H:\Documents\py\MpApi\sdata\KK-vanGogh\KK-vanGogh\20221125\KK-vanGogh-join-group154397.xml -xsl:\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\zml2lido\data\xsl\zml2lido.xsl -o:\\FS0002\Home\MDFRAHAG\Documents\py\zml2lido\sdata\KK-vanGogh\20221125\KK-vanGogh-join-group154397.lido.xml' returned non-zero exit status 1.

**Comment by mokko** [comment]
```
Error occurred during initialization of VM
Could not reserve enough space for 1484800KB object heap
```

das ist der bekannte Fehler, dass nicht genug RAM vorhanden ist. Outlook und Acrobat aus , dann müsste es gehen.
